language: python
python:
  - "3.3"
  - "3.4"
install:
  - "pip install setuptools"
  - "pip install jinja2"
  - "pip install numpy"
  - "pip install pandas"
  - "pip install lifelines"
  - "pip install statsmodels"
script: "python setup.py test"
